name: Lint

on: [pull_request]

jobs:
  ruff-check:
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/ruff-action@v3
      with:
        args: check --target-version=py313
